Simple class with arithmetical methods, focused on exceptions.
ReforgedDream/java_learning pull request #1
Opened 2018-12-02 19:36 UTC by ReforgedDream

A new project added. Work in progress: gonna add my own exception class and make sure that the factorial method generates StackOverflow or OutOfMemory.

2018-12-02 21:08 UTC, bass-2000 commented on exceptions/src/MathBox.java
> +        for(int i = 1; i <= i; i++) {
i<=i ?

2018-12-02 21:10 UTC, bass-2000 requested changes
в целом очень хорошо для первого ПР)

2018-12-06 05:23 UTC, bass-2000 approved these changes

2018-12-06 05:23 UTC, bass-2000 approved these changes

2018-12-18 13:25 UTC, bass-2000 commented
долго ПР будет висеть?)

2019-10-03 15:12 UTC, ReforgedDream commented on exceptions/src/MathBox.java
> +        for(int i = 1; i <= i; i++) {
Когда вычисляем факториал, нужно перемножить все числа от 1 до числа включительно)

2019-10-03 15:13 UTC, merged